
type jlModel
   m::Ptr{mjModel}

   qpos0::Ptr{mjtNum}
   qpos_spring::Ptr{mjtNum}
   body_parentid::Ptr{Cint}
   body_rootid::Ptr{Cint}
   body_weldid::Ptr{Cint}
   body_mocapid::Ptr{Cint}
   body_jntnum::Ptr{Cint}
   body_jntadr::Ptr{Cint}
   body_dofnum::Ptr{Cint}
   body_dofadr::Ptr{Cint}
   body_geomnum::Ptr{Cint}
   body_geomadr::Ptr{Cint}
   body_pos::Ptr{mjtNum}
   body_quat::Ptr{mjtNum}
   body_ipos::Ptr{mjtNum}
   body_iquat::Ptr{mjtNum}
   body_mass::Ptr{mjtNum}
   body_subtreemass::Ptr{mjtNum}
   body_inertia::Ptr{mjtNum}
   body_invweight0::Ptr{mjtNum}
   body_user::Ptr{mjtNum}
   jnt_type::Ptr{Cint}
   jnt_qposadr::Ptr{Cint}
   jnt_dofadr::Ptr{Cint}
   jnt_bodyid::Ptr{Cint}
   jnt_limited::Ptr{mjtByte}
   jnt_solref::Ptr{mjtNum}
   jnt_solimp::Ptr{mjtNum}
   jnt_pos::Ptr{mjtNum}
   jnt_axis::Ptr{mjtNum}
   jnt_stiffness::Ptr{mjtNum}
   jnt_range::Ptr{mjtNum}
   jnt_margin::Ptr{mjtNum}
   jnt_user::Ptr{mjtNum}
   dof_bodyid::Ptr{Cint}
   dof_jntid::Ptr{Cint}
   dof_parentid::Ptr{Cint}
   dof_Madr::Ptr{Cint}
   dof_frictional::Ptr{mjtByte}
   dof_solref::Ptr{mjtNum}
   dof_solimp::Ptr{mjtNum}
   dof_frictionloss::Ptr{mjtNum}
   dof_armature::Ptr{mjtNum}
   dof_damping::Ptr{mjtNum}
   dof_invweight0::Ptr{mjtNum}
   geom_type::Ptr{Cint}
   geom_contype::Ptr{Cint}
   geom_conaffinity::Ptr{Cint}
   geom_condim::Ptr{Cint}
   geom_bodyid::Ptr{Cint}
   geom_dataid::Ptr{Cint}
   geom_matid::Ptr{Cint}
   geom_group::Ptr{Cint}
   geom_solmix::Ptr{mjtNum}
   geom_solref::Ptr{mjtNum}
   geom_solimp::Ptr{mjtNum}
   geom_size::Ptr{mjtNum}
   geom_rbound::Ptr{mjtNum}
   geom_pos::Ptr{mjtNum}
   geom_quat::Ptr{mjtNum}
   geom_friction::Ptr{mjtNum}
   geom_margin::Ptr{mjtNum}
   geom_gap::Ptr{mjtNum}
   geom_user::Ptr{mjtNum}
   geom_rgba::Ptr{Cfloat}
   site_type::Ptr{Cint}
   site_bodyid::Ptr{Cint}
   site_matid::Ptr{Cint}
   site_group::Ptr{Cint}
   site_size::Ptr{mjtNum}
   site_pos::Ptr{mjtNum}
   site_quat::Ptr{mjtNum}
   site_user::Ptr{mjtNum}
   site_rgba::Ptr{Cfloat}
   cam_mode::Ptr{Cint}
   cam_bodyid::Ptr{Cint}
   cam_targetbodyid::Ptr{Cint}
   cam_pos::Ptr{mjtNum}
   cam_quat::Ptr{mjtNum}
   cam_poscom0::Ptr{mjtNum}
   cam_pos0::Ptr{mjtNum}
   cam_mat0::Ptr{mjtNum}
   cam_fovy::Ptr{mjtNum}
   cam_ipd::Ptr{mjtNum}
   light_mode::Ptr{Cint}
   light_bodyid::Ptr{Cint}
   light_targetbodyid::Ptr{Cint}
   light_directional::Ptr{mjtByte}
   light_castshadow::Ptr{mjtByte}
   light_active::Ptr{mjtByte}
   light_pos::Ptr{mjtNum}
   light_dir::Ptr{mjtNum}
   light_poscom0::Ptr{mjtNum}
   light_pos0::Ptr{mjtNum}
   light_dir0::Ptr{mjtNum}
   light_attenuation::Ptr{Cfloat}
   light_cutoff::Ptr{Cfloat}
   light_exponent::Ptr{Cfloat}
   light_ambient::Ptr{Cfloat}
   light_diffuse::Ptr{Cfloat}
   light_specular::Ptr{Cfloat}
   mesh_faceadr::Ptr{Cint}
   mesh_facenum::Ptr{Cint}
   mesh_vertadr::Ptr{Cint}
   mesh_vertnum::Ptr{Cint}
   mesh_graphadr::Ptr{Cint}
   mesh_vert::Ptr{Cfloat}
   mesh_normal::Ptr{Cfloat}
   mesh_face::Ptr{Cint}
   mesh_graph::Ptr{Cint}
   hfield_size::Ptr{mjtNum}
   hfield_nrow::Ptr{Cint}
   hfield_ncol::Ptr{Cint}
   hfield_adr::Ptr{Cint}
   hfield_data::Ptr{Cfloat}
   tex_type::Ptr{Cint}
   tex_height::Ptr{Cint}
   tex_width::Ptr{Cint}
   tex_adr::Ptr{Cint}
   tex_rgb::Ptr{mjtByte}
   mat_texid::Ptr{Cint}
   mat_texuniform::Ptr{mjtByte}
   mat_texrepeat::Ptr{Cfloat}
   mat_emission::Ptr{Cfloat}
   mat_specular::Ptr{Cfloat}
   mat_shininess::Ptr{Cfloat}
   mat_reflectance::Ptr{Cfloat}
   mat_rgba::Ptr{Cfloat}
   pair_dim::Ptr{Cint}
   pair_geom1::Ptr{Cint}
   pair_geom2::Ptr{Cint}
   pair_signature::Ptr{Cint}
   pair_solref::Ptr{mjtNum}
   pair_solimp::Ptr{mjtNum}
   pair_margin::Ptr{mjtNum}
   pair_gap::Ptr{mjtNum}
   pair_friction::Ptr{mjtNum}
   exclude_signature::Ptr{Cint}
   eq_type::Ptr{Cint}
   eq_obj1id::Ptr{Cint}
   eq_obj2id::Ptr{Cint}
   eq_active::Ptr{mjtByte}
   eq_solref::Ptr{mjtNum}
   eq_solimp::Ptr{mjtNum}
   eq_data::Ptr{mjtNum}
   tendon_adr::Ptr{Cint}
   tendon_num::Ptr{Cint}
   tendon_matid::Ptr{Cint}
   tendon_limited::Ptr{mjtByte}
   tendon_frictional::Ptr{mjtByte}
   tendon_width::Ptr{mjtNum}
   tendon_solref_lim::Ptr{mjtNum}
   tendon_solimp_lim::Ptr{mjtNum}
   tendon_solref_fri::Ptr{mjtNum}
   tendon_solimp_fri::Ptr{mjtNum}
   tendon_range::Ptr{mjtNum}
   tendon_margin::Ptr{mjtNum}
   tendon_stiffness::Ptr{mjtNum}
   tendon_damping::Ptr{mjtNum}
   tendon_frictionloss::Ptr{mjtNum}
   tendon_lengthspring::Ptr{mjtNum}
   tendon_length0::Ptr{mjtNum}
   tendon_invweight0::Ptr{mjtNum}
   tendon_user::Ptr{mjtNum}
   tendon_rgba::Ptr{Cfloat}
   wrap_type::Ptr{Cint}
   wrap_objid::Ptr{Cint}
   wrap_prm::Ptr{mjtNum}
   actuator_trntype::Ptr{Cint}
   actuator_dyntype::Ptr{Cint}
   actuator_gaintype::Ptr{Cint}
   actuator_biastype::Ptr{Cint}
   actuator_trnid::Ptr{Cint}
   actuator_ctrllimited::Ptr{mjtByte}
   actuator_forcelimited::Ptr{mjtByte}
   actuator_dynprm::Ptr{mjtNum}
   actuator_gainprm::Ptr{mjtNum}
   actuator_biasprm::Ptr{mjtNum}
   actuator_ctrlrange::Ptr{mjtNum}
   actuator_forcerange::Ptr{mjtNum}
   actuator_gear::Ptr{mjtNum}
   actuator_cranklength::Ptr{mjtNum}
   actuator_invweight0::Ptr{mjtNum}
   actuator_length0::Ptr{mjtNum}
   actuator_lengthrange::Ptr{mjtNum}
   actuator_user::Ptr{mjtNum}
   sensor_type::Ptr{Cint}
   sensor_datatype::Ptr{Cint}
   sensor_needstage::Ptr{Cint}
   sensor_objtype::Ptr{Cint}
   sensor_objid::Ptr{Cint}
   sensor_dim::Ptr{Cint}
   sensor_adr::Ptr{Cint}
   sensor_noise::Ptr{mjtNum}
   sensor_user::Ptr{mjtNum}
   numeric_adr::Ptr{Cint}
   numeric_size::Ptr{Cint}
   numeric_data::Ptr{mjtNum}
   text_adr::Ptr{Cint}
   text_size::Ptr{Cint}
   text_data::Ptr{UInt8}
   tuple_adr::Ptr{Cint}
   tuple_size::Ptr{Cint}
   tuple_objtype::Ptr{Cint}
   tuple_objid::Ptr{Cint}
   tuple_objprm::Ptr{mjtNum}
   key_time::Ptr{mjtNum}
   key_qpos::Ptr{mjtNum}
   key_qvel::Ptr{mjtNum}
   key_act::Ptr{mjtNum}
   name_bodyadr::Ptr{Cint}
   name_jntadr::Ptr{Cint}
   name_geomadr::Ptr{Cint}
   name_siteadr::Ptr{Cint}
   name_camadr::Ptr{Cint}
   name_lightadr::Ptr{Cint}
   name_meshadr::Ptr{Cint}
   name_hfieldadr::Ptr{Cint}
   name_texadr::Ptr{Cint}
   name_matadr::Ptr{Cint}
   name_eqadr::Ptr{Cint}
   name_tendonadr::Ptr{Cint}
   name_actuatoradr::Ptr{Cint}
   name_sensoradr::Ptr{Cint}
   name_numericadr::Ptr{Cint}
   name_textadr::Ptr{Cint}
   name_tupleadr::Ptr{Cint}
   names::Ptr{UInt8}
end

#mutable struct jlData # v0.6
type jlData
   d::Ptr{mjData} # point to c struct

   stack::Vector{mjtNum}
   qpos::Vector{mjtNum}
   qvel::Vector{mjtNum}
   act::Vector{mjtNum}
   ctrl::Vector{mjtNum}
   qfrc_applied::Vector{mjtNum}
   xfrc_applied::Vector{mjtNum}
   qacc::Vector{mjtNum}
   act_dot::Vector{mjtNum}
   mocap_pos::Vector{mjtNum}
   mocap_quat::Vector{mjtNum}
   userdata::Vector{mjtNum}
   sensordata::Vector{mjtNum}
   xpos::Vector{mjtNum}
   xquat::Vector{mjtNum}
   xmat::Vector{mjtNum}
   xipos::Vector{mjtNum}
   ximat::Vector{mjtNum}
   xanchor::Vector{mjtNum}
   xaxis::Vector{mjtNum}
   geom_xpos::Vector{mjtNum}
   geom_xmat::Vector{mjtNum}
   site_xpos::Vector{mjtNum}
   site_xmat::Vector{mjtNum}
   cam_xpos::Vector{mjtNum}
   cam_xmat::Vector{mjtNum}
   light_xpos::Vector{mjtNum}
   light_xdir::Vector{mjtNum}
   subtree_com::Vector{mjtNum}
   cdof::Vector{mjtNum}
   cinert::Vector{mjtNum}
   ten_wrapadr::Vector{Cint}
   ten_wrapnum::Vector{Cint}
   ten_length::Vector{mjtNum}
   ten_moment::Vector{mjtNum}
   wrap_obj::Vector{Cint}
   wrap_xpos::Vector{mjtNum}
   actuator_length::Vector{mjtNum}
   actuator_moment::Vector{mjtNum}
   crb::Vector{mjtNum}
   qM::Vector{mjtNum}
   qLD::Vector{mjtNum}
   qLDiagInv::Vector{mjtNum}
   qLDiagSqrtInv::Vector{mjtNum}
   contact::Vector{mjContact} #TODO test for this...
   efc_type::Vector{Cint}
   efc_id::Vector{Cint}
   efc_rownnz::Vector{Cint}
   efc_rowadr::Vector{Cint}
   efc_colind::Vector{Cint}
   efc_rownnz_T::Vector{Cint}
   efc_rowadr_T::Vector{Cint}
   efc_colind_T::Vector{Cint}
   efc_solref::Vector{mjtNum}
   efc_solimp::Vector{mjtNum}
   efc_margin::Vector{mjtNum}
   efc_frictionloss::Vector{mjtNum}
   efc_pos::Vector{mjtNum}
   efc_J::Vector{mjtNum}
   efc_J_T::Vector{mjtNum}
   efc_diagApprox::Vector{mjtNum}
   efc_D::Vector{mjtNum}
   efc_R::Vector{mjtNum}
   efc_AR::Vector{mjtNum}
   e_ARchol::Vector{mjtNum}
   fc_e_rect::Vector{mjtNum}
   fc_AR::Vector{mjtNum}
   ten_velocity::Vector{mjtNum}
   actuator_velocity::Vector{mjtNum}
   cvel::Vector{mjtNum}
   cdof_dot::Vector{mjtNum}
   qfrc_bias::Vector{mjtNum}
   qfrc_passive::Vector{mjtNum}
   efc_vel::Vector{mjtNum}
   efc_aref::Vector{mjtNum}
   subtree_linvel::Vector{mjtNum}
   subtree_angmom::Vector{mjtNum}
   actuator_force::Vector{mjtNum}
   qfrc_actuator::Vector{mjtNum}
   qfrc_unc::Vector{mjtNum}
   qacc_unc::Vector{mjtNum}
   efc_b::Vector{mjtNum}
   fc_b::Vector{mjtNum}
   efc_force::Vector{mjtNum}
   qfrc_constraint::Vector{mjtNum}
   qfrc_inverse::Vector{mjtNum}
   cacc::Vector{mjtNum}
   cfrc_int::Vector{mjtNum}
   cfrc_ext::Vector{mjtNum}
end

# added stack field manually
# manually did second terms in the parantheses
# TODO will be issues with the row-wise matrix fields vs the col major of julia
function getdatasize(m::mjModel, d::mjData)
   return Dict(
               :stack=>(d.nstack),
               :qpos=>(m.nq*1),
               :qvel=>(m.nv*1),
               :act=>(m.na*1),
               :ctrl=>(m.nu*1),
               :qfrc_applied=>(m.nv*1),
               :xfrc_applied=>(m.nbody*6),
               :qacc=>(m.nv*1),
               :act_dot=>(m.na*1),
               :mocap_pos=>(m.nmocap*3),
               :mocap_quat=>(m.nmocap*4),
               :userdata=>(m.nuserdata*1),
               :sensordata=>(m.nsensordata*1),
               :xpos=>(m.nbody*3),
               :xquat=>(m.nbody*4),
               :xmat=>(m.nbody*9),
               :xipos=>(m.nbody*3),
               :ximat=>(m.nbody*9),
               :xanchor=>(m.njnt*3),
               :xaxis=>(m.njnt*3),
               :geom_xpos=>(m.ngeom*3),
               :geom_xmat=>(m.ngeom*9),
               :site_xpos=>(m.nsite*3),
               :site_xmat=>(m.nsite*9),
               :cam_xpos=>(m.ncam*3),
               :cam_xmat=>(m.ncam*9),
               :light_xpos=>(m.nlight*3),
               :light_xdir=>(m.nlight*3),
               :subtree_com=>(m.nbody*3),
               :cdof=>(m.nv*6),
               :cinert=>(m.nbody*10),
               :ten_wrapadr=>(m.ntendon*1),
               :ten_wrapnum=>(m.ntendon*1),
               :ten_length=>(m.ntendon*1),
               :ten_moment=>(m.ntendon*m.nv),
               :wrap_obj=>(m.nwrap*2*1),
               :wrap_xpos=>(m.nwrap*2*3),
               :actuator_length=>(m.nu*1),
               :actuator_moment=>(m.nu*m.nv),
               :crb=>(m.nbody*10),
               :qM=>(m.nM*1),
               :qLD=>(m.nM*1),
               :qLDiagInv=>(m.nv*1),
               :qLDiagSqrtInv=>(m.nv*1),
               :contact=>(m.nconmax*1),
               :efc_type=>(m.njmax*1),
               :efc_id=>(m.njmax*1),
               :efc_rownnz=>(m.njmax*1),
               :efc_rowadr=>(m.njmax*1),
               :efc_colind=>(m.njmax*m.nv),
               :efc_rownnz_T=>(m.nv*1),
               :efc_rowadr_T=>(m.nv*1),
               :efc_colind_T=>(m.nv*m.njmax),
               :efc_solref=>(m.njmax*mjNREF),
               :efc_solimp=>(m.njmax*mjNIMP),
               :efc_margin=>(m.njmax*1),
               :efc_frictionloss=>(m.njmax*1),
               :efc_pos=>(m.njmax*1),
               :efc_J=>(m.njmax*m.nv),
               :efc_J_T=>(m.nv*m.njmax),
               :efc_diagApprox=>(m.njmax*1),
               :efc_D=>(m.njmax*1),
               :efc_R=>(m.njmax*1),
               :efc_AR=>(m.njmax*m.njmax),
               :e_ARchol=>(m.nemax*m.nemax),
               :fc_e_rect=>(m.njmax*m.nemax),
               :fc_AR=>(m.njmax*m.njmax),
               :ten_velocity=>(m.ntendon*1),
               :actuator_velocity=>(m.nu*1),
               :cvel=>(m.nbody*6),
               :cdof_dot=>(m.nv*6),
               :qfrc_bias=>(m.nv*1),
               :qfrc_passive=>(m.nv*1),
               :efc_vel=>(m.njmax*1),
               :efc_aref=>(m.njmax*1),
               :subtree_linvel=>(m.nbody*3),
               :subtree_angmom=>(m.nbody*3),
               :actuator_force=>(m.nu*1),
               :qfrc_actuator=>(m.nv*1),
               :qfrc_unc=>(m.nv*1),
               :qacc_unc=>(m.nv*1),
               :efc_b=>(m.njmax*1),
               :fc_b=>(m.njmax*1),
               :efc_force=>(m.njmax*1),
               :qfrc_constraint=>(m.nv*1),
               :qfrc_inverse=>(m.nv*1),
               :cacc=>(m.nbody*6),
               :cfrc_int=>(m.nbody*6),
               :cfrc_ext=>(m.nbody*6)
              )
end

function getmodelsize(m::mjModel)
   return Dict(
               :qpos0=>(m.nq*1),
               :qpos_spring=>(m.nq*1),
               :body_parentid=>(m.nbody*1),
               :body_rootid=>(m.nbody*1),
               :body_weldid=>(m.nbody*1),
               :body_mocapid=>(m.nbody*1),
               :body_jntnum=>(m.nbody*1),
               :body_jntadr=>(m.nbody*1),
               :body_dofnum=>(m.nbody*1),
               :body_dofadr=>(m.nbody*1),
               :body_geomnum=>(m.nbody*1),
               :body_geomadr=>(m.nbody*1),
               :body_pos=>(m.nbody*3),
               :body_quat=>(m.nbody*4),
               :body_ipos=>(m.nbody*3),
               :body_iquat=>(m.nbody*4),
               :body_mass=>(m.nbody*1),
               :body_subtreemass=>(m.nbody*1),
               :body_inertia=>(m.nbody*3),
               :body_invweight0=>(m.nbody*2),
               :body_user=>(m.nbody*m.nuser_body),
               :jnt_type=>(m.njnt*1),
               :jnt_qposadr=>(m.njnt*1),
               :jnt_dofadr=>(m.njnt*1),
               :jnt_bodyid=>(m.njnt*1),
               :jnt_limited=>(m.njnt*1),
               :jnt_solref=>(m.njnt*mjNREF),
               :jnt_solimp=>(m.njnt*mjNIMP),
               :jnt_pos=>(m.njnt*3),
               :jnt_axis=>(m.njnt*3),
               :jnt_stiffness=>(m.njnt*1),
               :jnt_range=>(m.njnt*2),
               :jnt_margin=>(m.njnt*1),
               :jnt_user=>(m.njnt*nuser_jnt),
               :dof_bodyid=>(m.nv*1),
               :dof_jntid=>(m.nv*1),
               :dof_parentid=>(m.nv*1),
               :dof_Madr=>(m.nv*1),
               :dof_frictional=>(m.nv*1),
               :dof_solref=>(m.nv*mjNREF),
               :dof_solimp=>(m.nv*mjNIMP),
               :dof_frictionloss=>(m.nv*1),
               :dof_armature=>(m.nv*1),
               :dof_damping=>(m.nv*1),
               :dof_invweight0=>(m.nv*1),
               :geom_type=>(m.ngeom*1),
               :geom_contype=>(m.ngeom*1),
               :geom_conaffinity=>(m.ngeom*1),
               :geom_condim=>(m.ngeom*1),
               :geom_bodyid=>(m.ngeom*1),
               :geom_dataid=>(m.ngeom*1),
               :geom_matid=>(m.ngeom*1),
               :geom_group=>(m.ngeom*1),
               :geom_solmix=>(m.ngeom*1),
               :geom_solref=>(m.ngeom*mjNREF),
               :geom_solimp=>(m.ngeom*mjNIMP),
               :geom_size=>(m.ngeom*3),
               :geom_rbound=>(m.ngeom*1),
               :geom_pos=>(m.ngeom*3),
               :geom_quat=>(m.ngeom*4),
               :geom_friction=>(m.ngeom*3),
               :geom_margin=>(m.ngeom*1),
               :geom_gap=>(m.ngeom*1),
               :geom_user=>(m.ngeom*m.nuser_geom),
               :geom_rgba=>(m.ngeom*4),
               :site_type=>(m.nsite*1),
               :site_bodyid=>(m.nsite*1),
               :site_matid=>(m.nsite*1),
               :site_group=>(m.nsite*1),
               :site_size=>(m.nsite*3),
               :site_pos=>(m.nsite*3),
               :site_quat=>(m.nsite*4),
               :site_user=>(m.nsite*m.nuser_site),
               :site_rgba=>(m.nsite*4),
               :cam_mode=>(m.ncam*1),
               :cam_bodyid=>(m.ncam*1),
               :cam_targetbodyid=>(m.ncam*1),
               :cam_pos=>(m.ncam*3),
               :cam_quat=>(m.ncam*4),
               :cam_poscom0=>(m.ncam*3),
               :cam_pos0=>(m.ncam*3),
               :cam_mat0=>(m.ncam*9),
               :cam_fovy=>(m.ncam*1),
               :cam_ipd=>(m.ncam*1),
               :light_mode=>(m.nlight*1),
               :light_bodyid=>(m.nlight*1),
               :light_targetbodyid=>(m.nlight*1),
               :light_directional=>(m.nlight*1),
               :light_castshadow=>(m.nlight*1),
               :light_active=>(m.nlight*1),
               :light_pos=>(m.nlight*3),
               :light_dir=>(m.nlight*3),
               :light_poscom0=>(m.nlight*3),
               :light_pos0=>(m.nlight*3),
               :light_dir0=>(m.nlight*3),
               :light_attenuation=>(m.nlight*3),
               :light_cutoff=>(m.nlight*1),
               :light_exponent=>(m.nlight*1),
               :light_ambient=>(m.nlight*3),
               :light_diffuse=>(m.nlight*3),
               :light_specular=>(m.nlight*3),
               :mesh_faceadr=>(m.nmesh*1),
               :mesh_facenum=>(m.nmesh*1),
               :mesh_vertadr=>(m.nmesh*1),
               :mesh_vertnum=>(m.nmesh*1),
               :mesh_graphadr=>(m.nmesh*1),
               :mesh_vert=>(m.nmeshvert*3),
               :mesh_normal=>(m.nmeshvert*3),
               :mesh_face=>(m.nmeshface*3),
               :mesh_graph=>(m.nmeshgraph*1),
               :hfield_size=>(m.nhfield*4),
               :hfield_nrow=>(m.nhfield*1),
               :hfield_ncol=>(m.nhfield*1),
               :hfield_adr=>(m.nhfield*1),
               :hfield_data=>(m.nhfielddata*1),
               :tex_type=>(m.ntex*1),
               :tex_height=>(m.ntex*1),
               :tex_width=>(m.ntex*1),
               :tex_adr=>(m.ntex*1),
               :tex_rgb=>(m.ntexdata*1),
               :mat_texid=>(m.nmat*1),
               :mat_texuniform=>(m.nmat*1),
               :mat_texrepeat=>(m.nmat*2),
               :mat_emission=>(m.nmat*1),
               :mat_specular=>(m.nmat*1),
               :mat_shininess=>(m.nmat*1),
               :mat_reflectance=>(m.nmat*1),
               :mat_rgba=>(m.nmat*4),
               :pair_dim=>(m.npair*1),
               :pair_geom1=>(m.npair*1),
               :pair_geom2=>(m.npair*1),
               :pair_signature=>(m.npair*1),
               :pair_solref=>(m.npair*mjNREF),
               :pair_solimp=>(m.npair*mjNIMP),
               :pair_margin=>(m.npair*1),
               :pair_gap=>(m.npair*1),
               :pair_friction=>(m.npair*5),
               :exclude_signature=>(m.nexclude*1),
               :eq_type=>(m.neq*1),
               :eq_obj1id=>(m.neq*1),
               :eq_obj2id=>(m.neq*1),
               :eq_active=>(m.neq*1),
               :eq_solref=>(m.neq*mjNREF),
               :eq_solimp=>(m.neq*mjNIMP),
               :eq_data=>(m.neq*mjNEQDATA),
               :tendon_adr=>(m.ntendon*1),
               :tendon_num=>(m.ntendon*1),
               :tendon_matid=>(m.ntendon*1),
               :tendon_limited=>(m.ntendon*1),
               :tendon_frictional=>(m.ntendon*1),
               :tendon_width=>(m.ntendon*1),
               :tendon_solref_lim=>(m.ntendon*mjNREF),
               :tendon_solimp_lim=>(m.ntendon*mjNIMP),
               :tendon_solref_fri=>(m.ntendon*mjNREF),
               :tendon_solimp_fri=>(m.ntendon*mjNIMP),
               :tendon_range=>(m.ntendon*2),
               :tendon_margin=>(m.ntendon*1),
               :tendon_stiffness=>(m.ntendon*1),
               :tendon_damping=>(m.ntendon*1),
               :tendon_frictionloss=>(m.ntendon*1),
               :tendon_lengthspring=>(m.ntendon*1),
               :tendon_length0=>(m.ntendon*1),
               :tendon_invweight0=>(m.ntendon*1),
               :tendon_user=>(m.ntendon*m.nuser_tendon),
               :tendon_rgba=>(m.ntendon*4),
               :wrap_type=>(m.nwrap*1),
               :wrap_objid=>(m.nwrap*1),
               :wrap_prm=>(m.nwrap*1),
               :actuator_trntype=>(m.nu*1),
               :actuator_dyntype=>(m.nu*1),
               :actuator_gaintype=>(m.nu*1),
               :actuator_biastype=>(m.nu*1),
               :actuator_trnid=>(m.nu*2),
               :actuator_ctrllimited=>(m.nu*1),
               :actuator_forcelimited=>(m.nu*1),
               :actuator_dynprm=>(m.nu*mjNDYN),
               :actuator_gainprm=>(m.nu*mjNGAIN),
               :actuator_biasprm=>(m.nu*mjNBIAS),
               :actuator_ctrlrange=>(m.nu*2),
               :actuator_forcerange=>(m.nu*2),
               :actuator_gear=>(m.nu*6),
               :actuator_cranklength=>(m.nu*1),
               :actuator_invweight0=>(m.nu*1),
               :actuator_length0=>(m.nu*1),
               :actuator_lengthrange=>(m.nu*2),
               :actuator_user=>(m.nu*m.nuser_actuator),
               :sensor_type=>(m.nsensor*1),
               :sensor_datatype=>(m.nsensor*1),
               :sensor_needstage=>(m.nsensor*1),
               :sensor_objtype=>(m.nsensor*1),
               :sensor_objid=>(m.nsensor*1),
               :sensor_dim=>(m.nsensor*1),
               :sensor_adr=>(m.nsensor*1),
               :sensor_noise=>(m.nsensor*1),
               :sensor_user=>(m.nsensor*m.nuser_sensor),
               :numeric_adr=>(m.nnumeric*1),
               :numeric_size=>(m.nnumeric*1),
               :numeric_data=>(m.nnumericdata*1),
               :text_adr=>(m.ntext*1),
               :text_size=>(m.ntext*1),
               :text_data=>(m.ntextdata*1),
               :tuple_adr=>(m.ntuple*1),
               :tuple_size=>(m.ntuple*1),
               :tuple_objtype=>(m.ntupledata*1),
               :tuple_objid=>(m.ntupledata*1),
               :tuple_objprm=>(m.ntupledata*1),
               :key_time=>(m.nkey*1),
               :key_qpos=>(m.nkey*m.nq),
               :key_qvel=>(m.nkey*m.nv),
               :key_act=>(m.nkey*m.na),
               :name_bodyadr=>(m.nbody*1),
               :name_jntadr=>(m.njnt*1),
               :name_geomadr=>(m.ngeom*1),
               :name_siteadr=>(m.nsite*1),
               :name_camadr=>(m.ncam*1),
               :name_lightadr=>(m.nlight*1),
               :name_meshadr=>(m.nmesh*1),
               :name_hfieldadr=>(m.nhfield*1),
               :name_texadr=>(m.ntex*1),
               :name_matadr=>(m.nmat*1),
               :name_eqadr=>(m.neq*1),
               :name_tendonadr=>(m.ntendon*1),
               :name_actuatoradr=>(m.nu*1),
               :name_sensoradr=>(m.nsensor*1),
               :name_numericadr=>(m.nnumeric*1),
               :name_textadr=>(m.ntext*1),
               :name_tupleadr=>(m.ntuple*1),
               :names=>(m.nnames*1)
              )
end



